version: '3.8'

services:
  web:
    container_name: celebration_devops_final
    image: gold1998/celebration_devops_final:latest
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/celebration
    ports:
      - "80:3001"
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data: