- name: Destroy app infrastructure on cloud
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/env
  vars:
    ansible_host_key_checking: false
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        state: absent
        region: "{{ aws_region }}"
        instance_ids: "{{ lookup('ansible.builtin.file', 'group_vars/colman.env') | regex_search('server_id: (i-[a-zA-Z0-9]+)', '\\1') }}"
      ignore_errors: true

    - name: Delete security group
      amazon.aws.ec2_group:
        name: "{{ vpc_name }} VPC SG"
        region: "{{ aws_region }}"
        state: absent
        vpc_id: "{{ lookup('ansible.builtin.file', 'group_vars/colman.env') | regex_search('vpc_id: (vpc-[a-zA-Z0-9]+)', '\\1') }}"
      ignore_errors: true

    - name: Detach and delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ aws_region }}"
        vpc_id: "{{ lookup('ansible.builtin.file', 'group_vars/colman.env') | regex_search('vpc_id: (vpc-[a-zA-Z0-9]+)', '\\1') }}"
        gateway_id: "{{ lookup('ansible.builtin.file', 'group_vars/colman.env') | regex_search('igw_id: (igw-[a-zA-Z0-9]+)', '\\1') }}"
        state: absent
      ignore_errors: true

    - name: Delete route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ aws_region }}"
        vpc_id: "{{ lookup('ansible.builtin.file', 'group_vars/colman.env') | regex_search('vpc_id: (vpc-[a-zA-Z0-9]+)', '\\1') }}"
        state: absent
        tags:
          Name: "{{ vpc_name }}public_rt"
      ignore_errors: true

    - name: Delete subnet
      amazon.aws.ec2_vpc_subnet:
        region: "{{ aws_region }}"
        vpc_id: "{{ lookup('ansible.builtin.file', 'group_vars/colman.env') | regex_search('vpc_id: (vpc-[a-zA-Z0-9]+)', '\\1') }}"
        subnet_id: "{{ lookup('ansible.builtin.file', 'group_vars/colman.env') | regex_search('subnet_id: (subnet-[a-zA-Z0-9]+)', '\\1') }}"
        state: absent
      ignore_errors: true

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        region: "{{ aws_region }}"
        vpc_id: "{{ lookup('ansible.builtin.file', 'group_vars/colman.env') | regex_search('vpc_id: (vpc-[a-zA-Z0-9]+)', '\\1') }}"
        state: absent
      ignore_errors: true

    - name: Clean up group_vars/colman.env
      ansible.builtin.lineinfile:
        path: group_vars/colman.env
        regexp: '^(vpc_id:|subnet_id:|igw_id:|server_id:)'
        state: absent
      ignore_errors: true