name: upload my image to DockerHub

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build --tag myapp .

      - name: Run Docker
        run: docker run -d --name app -e MONGO_URL=mongodb://host.docker.internal:27017/celebration -p 80:3001 myapp

      - name: Wait for server to be up
        run: |
          for i in {1..30}; do
            curl -sSf http://localhost:3001 && break
            echo "Waiting for server... ($i)"
            sleep 2
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install software
        run: sudo apt-get install -y chromium-browser

      - name: Install the necessary packages
        run: pip install requests webdriver_manager selenium pytest

      - name: Run the PyTest script
        run: pytest -rA