name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 27017 && echo "Mongo is up!" && break
            echo "Waiting for mongo... ($i)"
            sleep 3
          done

      - name: Seed products
        env:
          MONGO_URL: mongodb://localhost:27017/celebration
        run: node models/seedProducts.js

      - name: Start app and wait for server
        env:
          MONGO_URL: mongodb://localhost:27017/celebration
        run: |
          nohup npm start > server.log 2>&1 &
          for i in {1..30}; do
            sleep 3
            curl -fs http://localhost:3001 && echo "Server is up!" && break
            echo "Waiting for server... ($i)"
          done
          cat server.log

      - name: Show app logs if failed
        if: failure()
        run: cat server.log || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python requirements
        run: pip install selenium pytest webdriver-manager

      - name: Run Selenium tests
        run: pytest qa/test_selenium.py

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_token }}

      - name: Build Docker Image
        run: docker build . --tag reutp111/celebration-devops:latest

      - name: Push Docker Image
        run: docker push reutp111/celebration-devops:latest